services:
  ascribe:
    image: registry.sccs.swarthmore.edu/cs77-s25/ascribe/ascribe:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DOMAIN: https://ascribe.sccs.swarthmore.edu/
      POSTGRES_DB: ascribe_db
    env_file:
      - .env
    depends_on:
      - ascribe-db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.ascribe.entrypoints=https"
        - "traefik.http.routers.ascribe.rule=Host(`ascribe.sccs.swarthmore.edu`) && !PathPrefix('/studio')"
        - "traefik.http.routers.ascribe.tls=true"
        - "traefik.http.routers.ascribe.tls.certresolver=letsEncrypt"
        - "traefik.http.services.ascribe.loadbalancer.server.port=3000"
    networks:
      - traefik
      - internal
    command: sh -c "sleep 5 && npx prisma migrate deploy && npm start"

  ascribe-server:
    container_name: ascribe-server
    build:
      context: .
      dockerfile: ./Dockerfile.server
    env_file:
      - .env
    networks:
      - internal
  ascribe-db:
    image: postgres:16.4-bullseye
    restart: always
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname lists --username lists"]
      interval: 10s
      timeout: 5s
      retries: 5

  ascribe-studio:
    container_name: ascribe-studio
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - ascribe-db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.ascribestudio.entrypoints=https"
        - "traefik.http.routers.ascribestudio.rule=Host(`ascribe.sccs.swarthmore.edu`) && PathPrefix('/studio')"
        - "traefik.http.routers.ascribestudio.tls=true"
        - "traefik.http.routers.ascribestudio.tls.certresolver=letsEncrypt"
        - "traefik.http.services.ascribestudio.loadbalancer.server.port=5555"
    networks:
      - internal
      - traefik
    command: sh -c "sleep 10 && npx prisma studio"

volumes:
  pg_data:

networks:
  internal:
  traefik:
    external: true
