services:
  ascribe:
    image: registry.sccs.swarthmore.edu/cs77-s25/ascribe/ascribe:latest
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      #Mapping your current dir to the container so your changes can reload in real time
      - .:/usr/src/app
    environment:
      #Variables we use in the container
      #Nonsensitive ones can go here for dev
      #For prod put in .env file
      NODE_ENV: development
      DOMAIN: http://127.0.0.1:3000/
      POSTGRES_DB: ascribe_db
      DATABASE_URL: postgresql://postgres:example@ascribe-db:5432/ascribe_db
      #Due to docker networking we can reference the db by its container_name
    #env_file:
    #  - .env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.ascribe.entrypoints=https"
        - "traefik.http.routers.ascribe.rule=Host(`ascribe.sccs.swarthmore.edu`)"
        - "traefik.http.routers.ascribe.tls=true"
        - "traefik.http.routers.ascribe.tls.certresolver=letsEncrypt"
        - "traefik.http.services.ascribe.loadbalancer.server.port=3000"
    networks:
      - internal
    command: sh -c "npm install --silent && npx prisma migrate dev --name init && npx prisma generate && npm run dev"

  ascribe-db:
    image: postgres:16.4-bullseye
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ascribe_db
    networks:
      - internal
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  internal:
